
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package starkemulator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R10 = 32;
  public static final int Comma = 46;
  public static final int Or = 7;
  public static final int ClKey = 41;
  public static final int Hexadecimal = 45;
  public static final int SemCo = 44;
  public static final int Lb = 12;
  public static final int Points = 48;
  public static final int J = 21;
  public static final int OpPar = 38;
  public static final int Shr = 10;
  public static final int Shl = 9;
  public static final int Lmw = 16;
  public static final int Xor = 8;
  public static final int OpKey = 40;
  public static final int ID = 43;
  public static final int Jne = 18;
  public static final int EOF = 0;
  public static final int And = 5;
  public static final int Tag = 47;
  public static final int error = 1;
  public static final int Smw = 15;
  public static final int Jgt = 20;
  public static final int Num = 42;
  public static final int R9 = 31;
  public static final int R8 = 30;
  public static final int Min = 3;
  public static final int R7 = 29;
  public static final int Sw = 13;
  public static final int R6 = 28;
  public static final int R5 = 27;
  public static final int R4 = 26;
  public static final int R3 = 25;
  public static final int R2 = 24;
  public static final int R1 = 23;
  public static final int R0 = 22;
  public static final int Mul = 4;
  public static final int Je = 17;
  public static final int Nand = 6;
  public static final int ClPar = 39;
  public static final int Sb = 11;
  public static final int Lw = 14;
  public static final int Plus = 2;
  public static final int R15 = 37;
  public static final int R14 = 36;
  public static final int Jlt = 19;
  public static final int R13 = 35;
  public static final int R12 = 34;
  public static final int R11 = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Plus",
  "Min",
  "Mul",
  "And",
  "Nand",
  "Or",
  "Xor",
  "Shl",
  "Shr",
  "Sb",
  "Lb",
  "Sw",
  "Lw",
  "Smw",
  "Lmw",
  "Je",
  "Jne",
  "Jlt",
  "Jgt",
  "J",
  "R0",
  "R1",
  "R2",
  "R3",
  "R4",
  "R5",
  "R6",
  "R7",
  "R8",
  "R9",
  "R10",
  "R11",
  "R12",
  "R13",
  "R14",
  "R15",
  "OpPar",
  "ClPar",
  "OpKey",
  "ClKey",
  "Num",
  "ID",
  "SemCo",
  "Hexadecimal",
  "Comma",
  "Tag",
  "Points"
  };
}

